### ISSUE TITLE
Launcher error after closing game.

### ISSUE THREAD

**Issue by efinst0rm** [XLabsProject/launcher#113]
Hey,

Using the newest launcher on experimental branch will cause this error after playing any game and hitting quit from main menu.

![hfjNfu2N1zmpjBPGOLru](https://user-images.githubusercontent.com/7751074/137750981-fb4ccd96-b975-479f-b1c2-0f0620e0030c.png)

**Comment by mjkzy** [comment]
errors here?
https://github.com/XLabsProject/iw6x-client/blob/develop/src/client/main.cpp#L105

no clue why that happens if you quit the game

**Comment by efinst0rm** [comment]
Issue seems to have resolved itself with the newest experimental launcher build.

**Comment by mjkzy** [comment]
@efinst0rm all that was done was a typo fix and a CEF update
