### ISSUE TITLE
Pls help if you can    incorect syntex

### ISSUE THREAD

**Issue by jakolai** [XLabsProject/launcher#153]
This is after i open the launcher  and i dont have user name with 8:8 so help if you can
![изображение_2021-11-07_210605](https://user-images.githubusercontent.com/93881936/140658368-c68f4afc-71ae-4987-88e9-757639fb228a.png)

**Comment by Dss0** [comment]
this is most likely because of your windows username, as you can see in the error message it shows up as "8:8" but that's not your actual windows username right? Try changing your username to something that only contains ascii characters.

**Comment by jakolai** [comment]
I tride everything from changing file names to changing my windows user and it doesnt work

**Comment by Dss0** [comment]
related to #199

**Comment by diamante0018** [comment]
Should have been closed by #413
