### ISSUE TITLE
Issues with non-basic latin characters in filepaths

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/launcher#199]
Many users from foreign countries have non standard characters in their windows username or folders used to store the game or launcher. The launcher fails to handle those characters and therefore has issues creating it's folder structure in appdata.

Steps to reproduce:
- create windows user account containing non-basic latin character (e.g. Ó, Ñ, Ǟ)
- log into the new user account, download the launcher and try to start it

Behaviour: 
The launcher does not start up and creates a new user folder that it tries to store files to, this happens because it reads the characters of the original user folder as unreadable/unrecognized and therefore replaces them with "�". It then tries to create the folder structure using "�" instead of the original characters which results in a new user folder being created.

**Comment by diamante0018** [comment]
Closed by #409
