### ISSUE TITLE
Non Launcher Intergration

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/launcher#226]
Can we please get the old exes back without laucnher intergration. Ive had alot of people have issues with the laucnher either not opeing or their pcs notnletting them downlaod it. It also conflics with my Extinction server when it crashes beciase it no longer opens by itself after a crash. Personaly the laucher is great but alot of the time im not able to open it unless I kill the process the first few times after opening or using my laucher fix or even restarting my pc. I think alot if people would like it if you had the laucher as well as non laubcher intergrated exes for them to use as the exes in the appdata dont even let you start the game via batch fike anymore. Please concider this. -Soliderror

**Comment by Rackover** [comment]
Thanks for your report, but as you seem to be describing multiple different issues with the launcher I invite you to create one issue for each problem you're describing so that we can keep track of them appropriately. Feel free to add repro steps if there are any for easier fixing 🙂

**Comment by TheSoliderror** [comment]
> Thanks for your report, but as you seem to be describing multiple different issues with the launcher I invite you to create one issue for each problem you're describing so that we can keep track of them appropriately. Feel free to add repro steps if there are any for easier fixing 🙂 

There are two issues with the launcher as of now that people mainly complain about. I have 1 issue myself, the other I do not have as my name does not include non American characters. But the problems that are currently present are as follows: non-American characters in the users PC name will cause the launcher not to work at all. Issue 2: The laucher will get stuck in a process loop, causing the launcher to be running in the background while not running, this can happen either after an update or when you first try to start the launcher. A fix for this is running the CMD prompt: "taskkill /im xlabs.exe" this will kill the process faster then killing it task manager as there are at least 4 of the process open when this happens, and they jump around alot. Using that command normally fixes it the first time but sometimes you may have to run it 2 or 3 time before it actually lets you open it again.

**Comment by TheSoliderror** [comment]
I also tried to make a temporary fix to the game exes that worked for both the launcher and the local game files, but this got me banned in the xlabs discord, so I basically gave up on helping solve this issue.

**Comment by mjkzy** [comment]
> I also tried to make a temporary fix to the game exes

to be specific, the """temporary fix""" hadn't been a fix and a redistribution of the game exes with launcher support disabled.

**Comment by TheSoliderror** [comment]
> > I also tried to make a temporary fix to the game exes
> 
> to be specific, the """temporary fix""" hadn't been a fix and a redistribution of the game exes with launcher support disabled.
> 

That was the first time yes, I was talking about the pull request I added to add support for the launcher interaction and to be used in local files, I stopped distribution of the binary after I was warned to stop.
