### ISSUE TITLE
IW6X/S1X MP/Zombies/Extinction/Survival crashing on startup.

### ISSUE THREAD

**Issue by doshisgone** [XLabsProject/launcher#284]
i know this isnt really the place to report game-specific bugs, and really only for issues with the launcher, but i figured as this is an issue with both S1X and IW6X id give a shot at explaining it here.

to put it shortly, anything MP related (zm, survival, mp itself on S1X. Extinction and MP on IW6X) crashes out almost immediately. 

MP on IW6X was working fine until a couple of days ago (most likely after a windows update, i am a windows insider so it could just be a bug introduced in that), it just started crashing out (IW6X has stopped working, blah blah), while SP works fine.

its a similar situation with S1X too, SP loads fine, but the rest of the modes crash out with an error about not being able to map the binary, and that something is severely broken.

it could very well be an issue with Windows 11 itself, as i never had any issues playing S1X on my old Windows 10 install back in may 2021, and until very recently didnt have any issues with IW6X. weirdly if i turn off memory integrity on WIndows Denfender, the location it fails to map it to changes, so maybe again its an issue with Windows 11 itself? im not entirely sure.

if any more information is needed (crashdumps, logs, screenshots, etc) or if this issue is in the wrong places (again i didnt really know where to put it and i didnt wanna create issues in both S1X and IW6X's repos if the issue affects both games.), please let me know :)

**Comment by diamante0018** [comment]
Yes please create an issue on the game's repositories and update crash dumps there too.
Please verify first the game doesn't work for you before doing that. Thanks
