### ISSUE TITLE
Minimize and close window buttons have to be double-clicked rather than single-clicked to work

### ISSUE THREAD

**Issue by jmtn** [XLabsProject/launcher#315]
Pretty much just as the title says, I'm on Windows 10 v1809

**Comment by diamante0018** [comment]
https://support.microsoft.com/en-us/topic/windows-10-and-windows-server-2019-update-history-725fc2e1-4443-6831-a5ca-51ff5cbcb059

`IMPORTANT Windows 10, version 1809 reached end of service on November 10, 2020`

The launcher works fine for many other people on Windows 10.
Closing this as your version of Windows is no longer supported.
