### ISSUE TITLE
Launcher won't show MW2.

### ISSUE THREAD

**Issue by Jesskim0** [XLabsProject/launcher#347]
Launcher cuts off at Ghosts Installation so i can't configure my MW2 installation path
![IMG_2930 (1)](https://user-images.githubusercontent.com/107177137/172797659-1be76f30-54bf-4cc6-9637-0125dbb3dbf6.jpg)
.

**Comment by Jesskim0** [comment]
I cant scroll or expand the launcher window either.

**Comment by Karel1415** [comment]
I had the same problem. Solved by running xlabs.exe in compatibility mode for Windows8.
_(Running on Windows10, 2560*1440 LCD)_

**Comment by diamante0018** [comment]
Clone of #242
