### ISSUE TITLE
Launcher not installed

### ISSUE THREAD

**Issue by ApKaHa039** [XLabsProject/launcher#392]
I downloaded the launcher, installed it, and at the last percentage (the bands themselves do not download the files) and in the end it writes me this

Syntax error in file name, folder name, or volume label
(and there is also an installation path in which there is a folder that is not in my system)

<img width="960" alt="Desktop Screenshot 2022 08 06 - 22 26 31 91" src="https://user-images.githubusercontent.com/110743467/183265145-e0ae1602-4e3a-48a2-a59b-57795189b10b.png">

**Comment by Dss0** [comment]
the issue is you have special characters in your windows username, the launcher currently can't read anything besides standard latin characters.
