### ISSUE TITLE
iw6x tab should be similar to iw4x tab for size

### ISSUE THREAD

**Issue by mjkzy** [XLabsProject/launcher#393]
iw6x: 
![image](https://user-images.githubusercontent.com/64374267/183265230-00f961e5-ef51-41dd-b7c6-99f135f79d2b.png)

iw4x: 
![image](https://user-images.githubusercontent.com/64374267/183265225-33419be7-8635-4a9d-b533-8d7c7efb4ec7.png)

**Comment by diamante0018** [comment]
Close
