### ISSUE TITLE
Launcher reported as virus by McAfee on Windows 11

### ISSUE THREAD

**Issue by me-mariosteve** [XLabsProject/launcher#442]
On a recently owned Windows 11, I am following the guide to install IW4X without Steam at [IW4X Client Support](https://xlabs.dev/support_iw4x_client).
To download the launcher, I go to https://xlabs.dev/launcher, the URL of the download button is https://master.xlabs.dev/data/xlabs.exe. I put it in `C:\Users\<user>\Downloads` and start it as simple user (not admin). All seems fine, then after some seconds the window closes and McAfee tells me it stopped a virus. It deletes `xlabs.exe` and the log file. In the protection history, there's a code for the virus: `Real Protect.ci!DC94E7675D88`.
I've looked for informations about this on internet but there isn't anything, so I come here.

**Comment by efinst0rm** [comment]
That is a false positive.

**Comment by diamante0018** [comment]
Please read this https://xlabs.dev/antivirus

**Comment by me-mariosteve** [comment]
Thanks you very much! I apologize, I should have looked a bit more on the website.

**Comment by Rackover** [comment]
Frankly if it were up to me I would have the XLabs Launcher detect McAfee as a virus
