### ISSUE TITLE
Launcher stays open after update

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/launcher#48]
It seems after each update my launcher stays open in the task manger and does not close. I open the launcher and then the update window appears like normal, but after the update is complete the launcher does not start. Instead it stays open in the task manager until I end the task, I also cannot open the launcher unless I close it within the task manager as it will pop up "launcher already open" error. Here is also an image from after the most recent update. I look forward to the new launcher and keep up the great work. Also I should note I'm using experimental branch but this has also happened to me on stable. 
![Screenshot (14)](https://user-images.githubusercontent.com/83806741/126544222-05a3d640-c105-4549-b9b5-976b5b636ead.png)

**Comment by mjkzy** [comment]
windows 10 right?

**Comment by TheSoliderror** [comment]
Yes windows 10.

**Comment by TheSoliderror** [comment]
This has happened again with the most recent s1x.exe update for the launcher. I took two screenshots of the task manger, one as it was updating the other as it got done. It seems as the updater never closes and that the launcher tries to open, but never does. 
![Sceenshot after update](https://user-images.githubusercontent.com/83806741/126811147-1f1dc0c6-5b36-4183-be55-21c4c225f9b1.png)
![Screenshot of updater](https://user-images.githubusercontent.com/83806741/126811149-cf3b8ea2-8c23-4a0f-b422-6a71a60af1a4.png)

**Comment by TheSoliderror** [comment]
It also seems this happens after I close ghosts after opening it from the launcher, I closed the game, edited a script I'm working on  then tried to open the launcher again, and it gave me the "xlabs launcher already running" error, making me close it in the task manger once more. There are always two X Labs Launcher's running in the task manger as well when this happens.

**Comment by mjkzy** [comment]
this could be a long shot but maybe CEF is crashing somewhere and not terminating process? no clue. if i were you though, try searching for issues around Chrome Embedded Framework with what's happening.

**Comment by TheSoliderror** [comment]
Could you possibly add this simple batch to the exe? `@echo off
taskkill /F /im xlabs.exe` This is what I use now to kill the task faster, instead of using task manger.

**Comment by diamante0018** [comment]
Cannot replicate this bug.
Will close for now.
Please try again using the latest xlabs.exe
