### ISSUE TITLE
[BUG] Launcher Broken on Linux

### ISSUE THREAD

**Issue by papamikey** [XLabsProject/launcher#507]
Update near October seemed to break the Launcher. It updates like usual, but never opens. (Sits as a background process) As of November, I get this error. 
![image](https://user-images.githubusercontent.com/97386118/203607257-f964c5a7-ea55-43ff-8eee-9b0327a4b233.png)

While I'm here, is there any way to bypass the launcher?

**Comment by diamante0018** [comment]
Join the Xlabs discord, there are many solutions to this problem for each.
Do no open issues without checking the discord server first.
Xlabs launcher is a Windows application if it doesn't wok on Linux too bad.
