### ISSUE TITLE
Entry Point Not Found - Failed to load CEF

### ISSUE THREAD

**Issue by JohnDB** [XLabsProject/launcher#531]
This was working and recently stopped
I am getting this error when trying to launch the launcher - 

The procedure entry point NetFreeAadJoinInformation could not be located in the dynamic link library  C:\\... xlabs\cef\release\libcef.dll.

and then 

ERROR
Failed to load CEF

**Comment by diamante0018** [comment]
Hello, read this post please https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93.
For support queries, you must use the XLabs discord server.

**Comment by JohnDB** [comment]
Is it possible to get an old version of launcher? to run it on a win8?
